// Current WSR-88D site IDs exposed by the NWS per-radar GIS service directory.
// Keep this as a service allow-list so TDWR/retired/foreign radars in the broader
// radar_sites WFS feed do not become broken fast-lane markers.
export const WSR88D_IDS = Object.freeze(`
KABR KABX KAKQ KAMA KAMX KAPX KARX KATX KBBX KBGM
KBHX KBIS KBLX KBMX KBOX KBRO KBUF KBYX KCAE KCBW
KCBX KCCX KCLE KCLX KCRP KCXX KCYS KDAX KDDC KDFX
KDGX KDIX KDLH KDMX KDOX KDTX KDVN KDYX KEAX KEMX
KENX KEOX KEPZ KESX KEVX KEWX KEYX KFCX KFDR KFDX
KFFC KFSD KFSX KFTG KFWS KGGW KGJX KGLD KGRB KGRK
KGRR KGSP KGWX KGYX KHDC KHDX KHGX KHNX KHPX KHTX
KICT KICX KILN KILX KIND KINX KIWA KIWX KJAX KJGX
KJKL KLBB KLCH KLGX KLNX KLOT KLRX KLSX KLTX KLVX
KLWX KLZK KMAF KMAX KMBX KMHX KMKX KMLB KMOB KMPX
KMQT KMRX KMSX KMTX KMUX KMVX KMXX KNKX KNQA KOAX
KOHX KOKX KOTX KPAH KPBZ KPDT KPOE KPUX KRAX KRGX
KRIW KRLX KRTX KSFX KSGF KSHV KSJT KSOX KSRX KTBW
KTFX KTLH KTLX KTWX KTYX KUDX KUEX KVAX KVBX KVNX
KVTX KVWX KYUX PABC PACG PAEC PAHG PAIH PAKC PAPD
PGUA PHKI PHKM PHMO PHWA TJUA
`.trim().split(/\s+/));

export const WSR88D_ID_SET = new Set(WSR88D_IDS);
